name: release

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]' # this action will only run on tags that follow semver

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          body_path: release-notes.md
          generate_release_notes: false
          draft: true
          files: |
            docs/config-file.html
            docs/schema_doc.css
            schema_doc.min.js